services:
  - type: web
    name: uae-threat-monitor
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
